package view;

import cotroller.CtrLaporan;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.Parameter;

/**
 *
 * @author Edi Mariyanto
 */
public class LaporanStokBarang extends javax.swing.JInternalFrame {

    DefaultTableModel detail;

    /**
     * Creates new form LaporanStokBarang
     */
    public LaporanStokBarang() {
        initComponents();
        setTitle("Laporan Stok Barang");
        jxdTanggal.setFormats(Parameter.formatDate);
        jxdTanggal.setDate(new Date());
        lblFormat.setText("(" + Parameter.formatDate.toUpperCase() + ")");
        setDefaultTbl();
        setVisible(true);
    }

    private void setDefaultTbl() {
        detail = new DefaultTableModel();
        detail.addColumn("Kode Barang");
        detail.addColumn("Merk Barang");
        detail.addColumn("Jumlah");
        detail.addColumn("Satuan");
        setModelTbl();
    }

    private void setModelTbl() {
        tblStock.setModel(detail);
        tblStock.getColumnModel().getColumn(2).setCellRenderer(Parameter.rightRenderer());
        tblStock.setEnabled(false);
    }

    private void tampilkanStok() {
        CtrLaporan cl = new CtrLaporan();
        cl.setTanggal(jxdTanggal.getDate());
        cl.setKodeBarang(txtKode.getText().trim());
        cl.setMerkBarang(txtMerk.getText().trim());
        setDefaultTbl();
        DefaultTableModel dtm = cl.getLaporanStok();
        Integer jumlah = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            Object[] o = new Object[4];
            o[0] = dtm.getValueAt(i, 0).toString();
            o[1] = dtm.getValueAt(i, 1).toString();
            jumlah = Integer.parseInt(dtm.getValueAt(i, 2).toString());
            o[2] = jumlah;
            o[3] = dtm.getValueAt(i, 3).toString();
            detail.addRow(o);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        lblTanggal = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblMerk = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        jxdTanggal = new org.jdesktop.swingx.JXDatePicker();
        btnTampilkan = new javax.swing.JButton();
        lblFormat = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStock);

        lblTanggal.setText("Tanggal :");

        lblKode.setText("Kode Barang :");

        lblMerk.setText("Merk Barang :");

        btnTampilkan.setMnemonic('T');
        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        lblFormat.setText("()");

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMerk, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMerk)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtKode, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jxdTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblFormat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTampilkan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCetak)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(jxdTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampilkan)
                    .addComponent(btnCetak))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        tampilkanStok();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        tampilkanStok();
        CtrLaporan cl = new CtrLaporan();
        cl.setTanggal(jxdTanggal.getDate());
        cl.setKodeBarang(txtKode.getText().trim());
        cl.setMerkBarang(txtMerk.getText().trim());
        cl.cetakLaporanStok();
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxdTanggal;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblMerk;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMerk;
    // End of variables declaration//GEN-END:variables

}
