package view;

import cotroller.CtrLaporan;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.Parameter;

/**
 *
 * @author Edi Mariyanto
 */
public class LaporanTransaksiPerBarang extends javax.swing.JInternalFrame {

    DefaultTableModel detail;

    /**
     * Creates new form LaporanStokBarang
     */
    public LaporanTransaksiPerBarang() {
        initComponents();
        setTitle("Laporan Transaksi Per Barang");
        jxdTglDari.setFormats(Parameter.formatDate);
        jxdTglDari.setDate(new Date());
        lblFormatDari.setText("(" + Parameter.formatDate.toUpperCase() + ")");
        jxdTglSampai.setFormats(Parameter.formatDate);
        jxdTglSampai.setDate(new Date());
        lblFormatSampai.setText("(" + Parameter.formatDate.toUpperCase() + ")");
        setDefaultTbl();
        setVisible(true);
    }

    private void setDefaultTbl() {
        detail = new DefaultTableModel();
        detail.addColumn("Kode Barang");
        detail.addColumn("Merk Barang");
        detail.addColumn("Type");
        detail.addColumn("Tanggal");
        detail.addColumn("Kode Trans");
        detail.addColumn("Nomor Nota");
        detail.addColumn("Jumlah");
        detail.addColumn("Satuan");
        detail.addColumn("Harga");
        detail.addColumn("Referensi");
        setModelTbl();
    }

    private void setModelTbl() {
        tblTransaksi.setModel(detail);
        tblTransaksi.getColumnModel().getColumn(3).setCellRenderer(Parameter.dateRenderer());
        tblTransaksi.getColumnModel().getColumn(6).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.getColumnModel().getColumn(8).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.setEnabled(false);
    }

    private void tampilkanTransaksiPerBarang() {
        CtrLaporan cl = new CtrLaporan();
        cl.setTanggal(jxdTglDari.getDate());
        cl.setTanggal2(jxdTglSampai.getDate());
        cl.setKodeBarang(txtKode.getText().trim());
        cl.setMerkBarang(txtMerk.getText().trim());
        setDefaultTbl();
        DefaultTableModel dtm = cl.getLaporanTransaksiPerBarang();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            Object[] o = new Object[10];
            for (int j = 0; j < 10; j++) {
                o[j] = dtm.getValueAt(i, j).toString();
            }
            detail.addRow(o);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        lblTglDari = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblMerk = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        jxdTglDari = new org.jdesktop.swingx.JXDatePicker();
        btnTampilkan = new javax.swing.JButton();
        lblFormatDari = new javax.swing.JLabel();
        lblTglSampai = new javax.swing.JLabel();
        jxdTglSampai = new org.jdesktop.swingx.JXDatePicker();
        lblFormatSampai = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        lblTglDari.setText("Dari Tgl :");

        lblKode.setText("Kode Barang :");

        lblMerk.setText("Merk Barang :");

        btnTampilkan.setMnemonic('T');
        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        lblFormatDari.setText("()");

        lblTglSampai.setText("Sampai Tgl :");

        lblFormatSampai.setText("()");

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTglDari, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMerk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTglSampai, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnTampilkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCetak))
                            .addComponent(txtMerk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jxdTglDari, javax.swing.GroupLayout.PREFERRED_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jxdTglSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtKode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFormatDari, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(lblFormatSampai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(333, 333, 333))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTglDari)
                    .addComponent(jxdTglDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormatDari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTglSampai)
                    .addComponent(jxdTglSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormatSampai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampilkan)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        tampilkanTransaksiPerBarang();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        tampilkanTransaksiPerBarang();
        CtrLaporan cl = new CtrLaporan();
        cl.setTanggal(jxdTglDari.getDate());
        cl.setTanggal2(jxdTglSampai.getDate());
        cl.setKodeBarang(txtKode.getText().trim());
        cl.setMerkBarang(txtMerk.getText().trim());
        cl.cetakLaporanTransaksiPerBarang();
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxdTglDari;
    private org.jdesktop.swingx.JXDatePicker jxdTglSampai;
    private javax.swing.JLabel lblFormatDari;
    private javax.swing.JLabel lblFormatSampai;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblMerk;
    private javax.swing.JLabel lblTglDari;
    private javax.swing.JLabel lblTglSampai;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMerk;
    // End of variables declaration//GEN-END:variables

}
