package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Edi Mariyanto
 */
public class MainMenu extends javax.swing.JFrame {

    DaftarBarang daftarBarang;
    DaftarKaryawan daftarKaryawan;
    DaftarTransaksiPenjualan daftarTransaksiJual;
    DaftarTransaksiPenjualan2 daftarTransaksiJual2;
    DaftarTransaksiPembelian2 daftarTransaksiBeli2;
    TransaksiPenjualan jual;
    TransaksiPembelian beli;
    LaporanStokBarang stok;
    LaporanTransaksiPerBarang perbarang;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        //another confirm before exit
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                beforeExit();
            }
        });

        //show
        setVisible(true);
        //set maximize window
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        //set loading/progress
        pb.setValue(10);
        pb.setStringPainted(true);
        //set title
        String title = "Apotek System - GenInova";
        setTitle(title);
        pb.setValue(20);
        //set to center screen
        setLocationRelativeTo(null);
        pb.setValue(30);
        Login login = new Login();
        String status = "Logged In as " + login.getKaryawan().getNama() + " (" + login.getKaryawan().getJabatan() + ")";
        setTitle(title + " | " + status);
        pb.setValue(40);
        //add all view to DesktopPane 
        daftarBarang = new DaftarBarang();
        daftarBarang.setVisible(false);
        desktopUtama.add(daftarBarang);
        pb.setValue(50);
        daftarKaryawan = new DaftarKaryawan();
        daftarKaryawan.setVisible(false);
        desktopUtama.add(daftarKaryawan);
        pb.setValue(60);
        daftarTransaksiJual = new DaftarTransaksiPenjualan();
        daftarTransaksiJual.setVisible(false);
        desktopUtama.add(daftarTransaksiJual);
        pb.setValue(70);
        daftarTransaksiJual2 = new DaftarTransaksiPenjualan2();
        daftarTransaksiJual2.setVisible(false);
        desktopUtama.add(daftarTransaksiJual2);
        pb.setValue(80);
        daftarTransaksiBeli2 = new DaftarTransaksiPembelian2();
        daftarTransaksiBeli2.setVisible(false);
        desktopUtama.add(daftarTransaksiBeli2);
        pb.setValue(85);
        jual = new TransaksiPenjualan(login.getKaryawan().getUsername());
        jual.setVisible(false);
        desktopUtama.add(jual);
        pb.setValue(90);
        beli = new TransaksiPembelian();
        beli.setVisible(false);
        desktopUtama.add(beli);
        pb.setValue(95);
        stok = new LaporanStokBarang();
        stok.setVisible(false);
        desktopUtama.add(stok);
        pb.setValue(98);
        perbarang = new LaporanTransaksiPerBarang();
        perbarang.setVisible(false);
        desktopUtama.add(perbarang);
        pb.setValue(100);
        pb.setValue(0);
        //pb.setString(status);
        pb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        desktopUtama = new javax.swing.JDesktopPane();
        pb = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        miJual = new javax.swing.JMenuItem();
        miBeli = new javax.swing.JMenuItem();
        menuDaftar = new javax.swing.JMenu();
        miBarang = new javax.swing.JMenuItem();
        miTransaksiJual = new javax.swing.JMenuItem();
        miTransaksiJual2 = new javax.swing.JMenuItem();
        miTransaksiBeli2 = new javax.swing.JMenuItem();
        miKaryawan = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        miStokBarang = new javax.swing.JMenuItem();
        miTransPerBarang = new javax.swing.JMenuItem();
        menuWindow = new javax.swing.JMenu();
        miClear = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        desktopUtama.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout desktopUtamaLayout = new javax.swing.GroupLayout(desktopUtama);
        desktopUtama.setLayout(desktopUtamaLayout);
        desktopUtamaLayout.setHorizontalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        desktopUtamaLayout.setVerticalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(desktopUtama);

        menuFile.setMnemonic('F');
        menuFile.setText("File");

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miExit.setMnemonic('E');
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuFile.add(miExit);

        jMenuBar1.add(menuFile);

        menuTransaksi.setMnemonic('T');
        menuTransaksi.setText("Transaksi");

        miJual.setMnemonic('J');
        miJual.setText("Jual");
        miJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJualActionPerformed(evt);
            }
        });
        menuTransaksi.add(miJual);

        miBeli.setMnemonic('B');
        miBeli.setText("Beli");
        miBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBeliActionPerformed(evt);
            }
        });
        menuTransaksi.add(miBeli);

        jMenuBar1.add(menuTransaksi);

        menuDaftar.setMnemonic('D');
        menuDaftar.setText("Daftar");

        miBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        miBarang.setMnemonic('B');
        miBarang.setText("Daftar Barang");
        miBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBarangActionPerformed(evt);
            }
        });
        menuDaftar.add(miBarang);

        miTransaksiJual.setMnemonic('T');
        miTransaksiJual.setText("Daftar Transaksi Jual");
        miTransaksiJual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        miTransaksiJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransaksiJualActionPerformed(evt);
            }
        });
        menuDaftar.add(miTransaksiJual);

        miTransaksiJual2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        miTransaksiJual2.setMnemonic('J');
        miTransaksiJual2.setText("Daftar Transaksi Jual 2");
        miTransaksiJual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransaksiJual2ActionPerformed(evt);
            }
        });
        menuDaftar.add(miTransaksiJual2);

        miTransaksiBeli2.setText("Daftar Transaksi Beli 2");
        miTransaksiBeli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransaksiBeli2ActionPerformed(evt);
            }
        });
        menuDaftar.add(miTransaksiBeli2);

        miKaryawan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        miKaryawan.setMnemonic('K');
        miKaryawan.setText("Daftar Karyawan");
        miKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKaryawanActionPerformed(evt);
            }
        });
        menuDaftar.add(miKaryawan);

        jMenuBar1.add(menuDaftar);

        menuLaporan.setMnemonic('L');
        menuLaporan.setText("Laporan");

        miStokBarang.setMnemonic('S');
        miStokBarang.setText("Stok Barang");
        miStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStokBarangActionPerformed(evt);
            }
        });
        menuLaporan.add(miStokBarang);

        miTransPerBarang.setMnemonic('T');
        miTransPerBarang.setText("Transaksi Per Barang");
        miTransPerBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransPerBarangActionPerformed(evt);
            }
        });
        menuLaporan.add(miTransPerBarang);

        jMenuBar1.add(menuLaporan);

        menuWindow.setMnemonic('W');
        menuWindow.setText("Window");

        miClear.setMnemonic('C');
        miClear.setText("Clear All Windows");
        miClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClearActionPerformed(evt);
            }
        });
        menuWindow.add(miClear);

        jMenuBar1.add(menuWindow);

        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");

        miAbout.setMnemonic('A');
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        menuHelp.add(miAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        beforeExit();
    }//GEN-LAST:event_miExitActionPerformed

    private void beforeExit() {
        if (JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin akan keluar?", "Keluar Aplikasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void miBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBarangActionPerformed
        setTampilanAktif("barang");
    }//GEN-LAST:event_miBarangActionPerformed

    private void miKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKaryawanActionPerformed
        setTampilanAktif("karyawan");
    }//GEN-LAST:event_miKaryawanActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        About about = new About(this);
    }//GEN-LAST:event_miAboutActionPerformed

    private void miTransaksiJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransaksiJualActionPerformed
        setTampilanAktif("transaksi_jual");
    }//GEN-LAST:event_miTransaksiJualActionPerformed

    private void miTransaksiJual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransaksiJual2ActionPerformed
        setTampilanAktif("transaksi_jual2");
    }//GEN-LAST:event_miTransaksiJual2ActionPerformed

    private void miJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJualActionPerformed
        setTampilanAktif("jual");
    }//GEN-LAST:event_miJualActionPerformed

    private void miBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBeliActionPerformed
        setTampilanAktif("beli");
    }//GEN-LAST:event_miBeliActionPerformed

    private void miClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClearActionPerformed
        setTampilanAktif("");
    }//GEN-LAST:event_miClearActionPerformed

    private void miStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStokBarangActionPerformed
        setTampilanAktif("stok");
    }//GEN-LAST:event_miStokBarangActionPerformed

    private void miTransPerBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransPerBarangActionPerformed
        setTampilanAktif("perbarang");
    }//GEN-LAST:event_miTransPerBarangActionPerformed

    private void miTransaksiBeli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransaksiBeli2ActionPerformed
        setTampilanAktif("transaksi_beli2");
    }//GEN-LAST:event_miTransaksiBeli2ActionPerformed

    private void setTampilanAktif(String menu) {
        daftarBarang.setVisible(false);
        daftarKaryawan.setVisible(false);
        daftarTransaksiJual.setVisible(false);
        daftarTransaksiJual2.setVisible(false);
        daftarTransaksiBeli2.setVisible(false);
        jual.setVisible(false);
        beli.setVisible(false);
        stok.setVisible(false);
        perbarang.setVisible(false);
        switch (menu) {
            case "barang":
                daftarBarang.setVisible(true);
                break;
            case "karyawan":
                daftarKaryawan.setVisible(true);
                break;
            case "transaksi_jual":
                daftarTransaksiJual.setVisible(true);
                break;
            case "transaksi_jual2":
                daftarTransaksiJual2.setVisible(true);
                break;
            case "transaksi_beli2":
                daftarTransaksiBeli2.setVisible(true);
                break;
            case "jual":
                jual.setVisible(true);
                break;
            case "beli":
                beli.setVisible(true);
                break;
            case "stok":
                stok.setVisible(true);
                break;
            case "perbarang":
                perbarang.setVisible(true);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopUtama;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuDaftar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenu menuWindow;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miBarang;
    private javax.swing.JMenuItem miBeli;
    private javax.swing.JMenuItem miClear;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miJual;
    private javax.swing.JMenuItem miKaryawan;
    private javax.swing.JMenuItem miStokBarang;
    private javax.swing.JMenuItem miTransPerBarang;
    private javax.swing.JMenuItem miTransaksiBeli2;
    private javax.swing.JMenuItem miTransaksiJual;
    private javax.swing.JMenuItem miTransaksiJual2;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
}
