package view;

import cotroller.CtrBarang;
import java.awt.event.KeyEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.Barang;
import model.Parameter;

/**
 *
 * @author Edi Mariyanto
 */
public class PilihBarang extends javax.swing.JDialog {

    Barang barang;

    public Barang getBarang() {
        return barang;
    }

    public void setBarang(Barang barang) {
        this.barang = barang;
    }

    /**
     * Creates new form CariBarang
     */
    public PilihBarang() {
        initComponents();
        setTitle("Pilih Barang");
        txtSearch.getDocument().addDocumentListener(
                new DocumentListener() {
                    @Override
                    public void insertUpdate(DocumentEvent de) {
                        cariBarang();
                    }

                    @Override
                    public void removeUpdate(DocumentEvent de) {
                        cariBarang();
                    }

                    @Override
                    public void changedUpdate(DocumentEvent de) {
                        cariBarang();
                    }
                }
        );
        barang = null;
        cariBarang();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setModal(true);
        setVisible(true);
    }

    private void cariBarang() {
        CtrBarang cb = new CtrBarang();
        cb.setMerk(txtSearch.getText());
        tblPilihBarang.setModel(cb.getModelCariAllBarang());
        tblPilihBarang.getColumnModel().getColumn(4).setCellRenderer(Parameter.rightRenderer());
        if (tblPilihBarang.getModel().getRowCount() > 0) {
            tblPilihBarang.setRowSelectionInterval(0, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPilihBarang = new javax.swing.JTable();

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        tblPilihBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPilihBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPilihBarangMouseClicked(evt);
            }
        });
        tblPilihBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPilihBarangKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPilihBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_DOWN) {
            if (tblPilihBarang.getModel().getRowCount() > 1) {
                tblPilihBarang.setRowSelectionInterval(1, 1);
                tblPilihBarang.requestFocus();
            }
        } else if (key == KeyEvent.VK_ENTER) {
            setBarang();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void tblPilihBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPilihBarangKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_UP) {
            if (tblPilihBarang.getModel().getRowCount() > 0) {
                if (tblPilihBarang.getSelectedRow() == 0) {
                    txtSearch.requestFocus();
                }
            }
        } else if (key == KeyEvent.VK_ENTER) {
            setBarang();
        }
    }//GEN-LAST:event_tblPilihBarangKeyPressed

    private void tblPilihBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPilihBarangMouseClicked
        if (evt.getClickCount() == 2) {
            setBarang();
        }
    }//GEN-LAST:event_tblPilihBarangMouseClicked

    private void setBarang() {
        int row = tblPilihBarang.getSelectedRow();
        if (row >= 0) {
            barang = new Barang();
            barang.setKode(tblPilihBarang.getModel().getValueAt(row, 0).toString());
            barang.setKodeDetail(tblPilihBarang.getModel().getValueAt(row, 1).toString());
            barang.setMerk(tblPilihBarang.getModel().getValueAt(row, 2).toString());
            barang.setUOM(tblPilihBarang.getModel().getValueAt(row, 3).toString());
            barang.setHarga(Double.parseDouble(tblPilihBarang.getModel().getValueAt(row, 4).toString()));
            setVisible(false);
        } else {
            barang = null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPilihBarang;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
