package view;

import cotroller.CtrTransaksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Parameter;

/**
 *
 * @author Edi Mariyanto
 */
public class TransaksiPenjualan extends javax.swing.JInternalFrame {

    DefaultTableModel detail;

    /**
     * Creates new form DaftarTransaksi
     */
    public TransaksiPenjualan() {
        initComponents();
        this.setTitle("Transaksi Penjualan");
        setDefaultTable();
        jxdTanggal.setFormats(Parameter.formatDate);
        jxdTanggal.setDate(new Date());
        lblFormat.setText("(" + Parameter.formatDate.toUpperCase() + ")");
        setVisible(true);
    }

    public TransaksiPenjualan(String username) {
        this();
        txtPenjual.setText(username);
        setVisible(true);
    }

    private void setDefaultTable() {
        detail = new DefaultTableModel();
        detail.addColumn("Kode Barang");
        detail.addColumn("Merk Barang");
        detail.addColumn("Harga");
        detail.addColumn("Jumlah");
        detail.addColumn("Total");
        setModelTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        lblJumlah = new javax.swing.JLabel();
        lblKodeBarang = new javax.swing.JLabel();
        lblMerk = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTanggal = new javax.swing.JLabel();
        lblNoNota = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtNoNota = new javax.swing.JTextField();
        btnPilihBarang = new javax.swing.JButton();
        jxdTanggal = new org.jdesktop.swingx.JXDatePicker();
        lblPenjual = new javax.swing.JLabel();
        txtPenjual = new javax.swing.JTextField();
        lblPesanBarang = new javax.swing.JLabel();
        lblPesanHarga = new javax.swing.JLabel();
        lblPesanJumlah = new javax.swing.JLabel();
        lblPesanDetail = new javax.swing.JLabel();
        lblPesanTanggal = new javax.swing.JLabel();
        lblPesanPenjual = new javax.swing.JLabel();
        lblPesanNoNota = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        lblJumlah.setText("Jumlah :");

        lblKodeBarang.setText("Kode Barang :");

        lblMerk.setText("Merk :");

        lblHarga.setText("Harga :");

        txtJumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtKodeBarang.setEditable(false);

        txtMerk.setEditable(false);

        txtHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblTanggal.setText("Tanggal :");

        lblNoNota.setText("Nomor Nota :");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnPilihBarang.setText("Pilih Barang");
        btnPilihBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihBarangActionPerformed(evt);
            }
        });

        lblPenjual.setText("Penjual :");

        txtPenjual.setEditable(false);

        lblPesanBarang.setForeground(new java.awt.Color(255, 0, 0));

        lblPesanHarga.setForeground(new java.awt.Color(255, 0, 0));

        lblPesanJumlah.setForeground(new java.awt.Color(255, 0, 0));

        lblPesanDetail.setForeground(new java.awt.Color(255, 0, 0));

        lblPesanTanggal.setForeground(new java.awt.Color(255, 0, 0));

        lblPesanPenjual.setForeground(new java.awt.Color(255, 0, 0));

        lblPesanNoNota.setForeground(new java.awt.Color(255, 0, 0));

        lblFormat.setText("()");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNoNota, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPenjual, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReset))
                                    .addComponent(txtPenjual)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNoNota))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jxdTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesanNoNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPesanPenjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblFormat)
                                .addGap(18, 18, 18)
                                .addComponent(lblPesanTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKodeBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMerk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHarga, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPilihBarang)
                                        .addGap(0, 88, Short.MAX_VALUE))
                                    .addComponent(lblPesanBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtHarga))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPesanHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPesanJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPesanDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKodeBarang)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMerk)
                        .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHarga)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesanHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJumlah)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesanJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblPesanDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTanggal)
                        .addComponent(jxdTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFormat))
                    .addComponent(lblPesanTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNoNota)
                        .addComponent(txtNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesanNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPenjual)
                            .addComponent(txtPenjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnReset)))
                    .addComponent(lblPesanPenjual, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihBarangActionPerformed
        PilihBarang pb = new PilihBarang();
        if (pb.getBarang() != null) {
            txtKodeBarang.setText(pb.getBarang().getKode() + pb.getBarang().getKodeDetail());
            txtMerk.setText(pb.getBarang().getMerk());
            txtHarga.setText(Double.toString(pb.getBarang().getHarga()));
            txtJumlah.setText("1");
        }
    }//GEN-LAST:event_btnPilihBarangActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearTxt();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (validasiTambah()) {
            Object[] o = new Object[5];
            o[0] = txtKodeBarang.getText();
            o[1] = txtMerk.getText();
            Double harga = Double.parseDouble(txtHarga.getText());
            Integer jumlah = Integer.parseInt(txtJumlah.getText());
            o[2] = harga;
            o[3] = jumlah;
            o[4] = harga * jumlah;
            detail.addRow(o);
            setModelTbl();
            clearTxt();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblTransaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseReleased
        klikKanan(evt);
    }//GEN-LAST:event_tblTransaksiMouseReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        if (JOptionPane.showConfirmDialog(this,
                "Yakin ingin reset?", "Reset", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            resetForm();
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validasiSimpan()) {
            CtrTransaksi ct;
            for (int i = 0; i < detail.getRowCount(); i++) {
                ct = new CtrTransaksi();
                ct.setKodeBarang(detail.getValueAt(i, 0).toString());
                ct.setHarga(Double.parseDouble(detail.getValueAt(i, 2).toString()));
                ct.setJumlah(Integer.parseInt(detail.getValueAt(i, 3).toString()));
                ct.setTgl(jxdTanggal.getDate());
                ct.setNomorNota(txtNoNota.getText());
                ct.setReferensi(txtPenjual.getText());
                ct.tambahTransaksiJual();
            }
            JOptionPane.showMessageDialog(this,
                    "Transaksi Jual berhasil disimpan", "Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            resetForm();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void resetForm() {
        clearTxt();
        for (int i = detail.getRowCount() - 1; i >= 0; i--) {
            detail.removeRow(i);
        }
        jxdTanggal.setDate(new Date());
        txtNoNota.setText("");
    }

    private boolean validasiSimpan() {
        boolean valid = true;
        lblPesanDetail.setText("");
        lblPesanNoNota.setText("");
        if (detail.getRowCount() == 0) {
            lblPesanDetail.setText("Detail belum diisi. ");
            valid = false;
        }
        if (txtNoNota.getText().equals("")) {
            lblPesanNoNota.setText("Nomor Nota belum diisi. ");
            valid = false;
        }
        return valid;
    }

    private void klikKanan(java.awt.event.MouseEvent e) {
        int r = tblTransaksi.rowAtPoint(e.getPoint());
        if (r >= 0 && r < tblTransaksi.getRowCount()) {
            tblTransaksi.setRowSelectionInterval(r, r);
        } else {
            tblTransaksi.clearSelection();
        }
        int rowindex = tblTransaksi.getSelectedRow();
        if (rowindex < 0) {
            return;
        }
        if (e.getComponent() instanceof JTable) { //only right click -> (e.isPopupTrigger() && e.getComponent() instanceof JTable)
            JPopupMenu popup = new JPopupMenu();
            JMenuItem deleteItem = new JMenuItem("Delete");
            deleteItem.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int rowindex = tblTransaksi.getSelectedRow();
                    detail.removeRow(rowindex);
                    setModelTbl();
                }
            });
            popup.add(deleteItem);
            popup.show(e.getComponent(), e.getX(), e.getY());
        }
    }

    private boolean validasiTambah() {
        boolean valid = true;
        lblPesanBarang.setText("");
        lblPesanHarga.setText("");
        lblPesanJumlah.setText("");
        if (txtKodeBarang.getText().equals("")) {
            lblPesanBarang.setText("Barang belum dipilih. ");
            valid = false;
        }
        if (!Parameter.isDouble(txtHarga.getText())) {
            lblPesanHarga.setText("Harga tidak valid. ");
            valid = false;
        }
        if (!Parameter.isInteger(txtJumlah.getText())) {
            lblPesanJumlah.setText("Jumlah tidak valid. ");
            valid = false;
        }
        return valid;
    }

    private void setModelTbl() {
        tblTransaksi.setModel(detail);
        tblTransaksi.getColumnModel().getColumn(2).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.getColumnModel().getColumn(3).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.getColumnModel().getColumn(4).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.setEnabled(false);
    }

    private void clearTxt() {
        txtJumlah.setText("");
        txtKodeBarang.setText("");
        txtMerk.setText("");
        txtHarga.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPenjualan("asd").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPilihBarang;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxdTanggal;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKodeBarang;
    private javax.swing.JLabel lblMerk;
    private javax.swing.JLabel lblNoNota;
    private javax.swing.JLabel lblPenjual;
    private javax.swing.JLabel lblPesanBarang;
    private javax.swing.JLabel lblPesanDetail;
    private javax.swing.JLabel lblPesanHarga;
    private javax.swing.JLabel lblPesanJumlah;
    private javax.swing.JLabel lblPesanNoNota;
    private javax.swing.JLabel lblPesanPenjual;
    private javax.swing.JLabel lblPesanTanggal;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtNoNota;
    private javax.swing.JTextField txtPenjual;
    // End of variables declaration//GEN-END:variables
}
