package view;

import cotroller.CtrTransaksi;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.Parameter;

/**
 *
 * @author Edi Mariyanto
 */
public class TransaksiDetail extends javax.swing.JDialog {

    DefaultTableModel detail;
    String nomorNota;
    String typeTransaksi;

    /**
     * Creates new form DaftarTransaksi
     */
    public TransaksiDetail() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultTable();
    }

    public TransaksiDetail(String type, String noNota) {
        this();
        String judul = "";
        if (type.equals("jual")) {
            judul = "Detail Transaksi Jual";
        } else if (type.equals("beli")) {
            judul = "Detail Transaksi Beli";
        }
        this.setTitle(judul);
        this.setTransaksiDetail(type, noNota);
        this.nomorNota = noNota;
        this.typeTransaksi = type;
        setModal(true);
        setVisible(true);
    }

    private void setTransaksiDetail(String type, String noNota) {
        CtrTransaksi ct = new CtrTransaksi();
        ct.setNomorNota(noNota);
        DefaultTableModel dtm = ct.getTransaksiDetail(type);
        txtTanggal.setText(Parameter.format().format((Date) dtm.getValueAt(0, 0)));
        lblFormat.setText("(" + Parameter.formatDate.toUpperCase() + ")");
        txtNoNota.setText(dtm.getValueAt(0, 2).toString());
        txtReferensi.setText(dtm.getValueAt(0, 8).toString());
        Double totalHarga = 0.0;
        Double harga = 0.0;
        Integer jumlah = 0;
        Double total = 0.0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            Object[] o = new Object[5];
            o[0] = dtm.getValueAt(i, 3).toString();
            o[1] = dtm.getValueAt(i, 4).toString();
            harga = Double.parseDouble(dtm.getValueAt(i, 5).toString());
            jumlah = Integer.parseInt(dtm.getValueAt(i, 6).toString());
            total = Double.parseDouble(dtm.getValueAt(i, 7).toString());
            totalHarga += total;
            o[2] = harga;
            o[3] = jumlah;
            o[4] = total;
            detail.addRow(o);
        }
        setModelTbl();
        lblTotalHarga.setText(totalHarga.toString());
    }

    private void setDefaultTable() {
        detail = new DefaultTableModel();
        detail.addColumn("Kode Barang");
        detail.addColumn("Merk Barang");
        detail.addColumn("Harga");
        detail.addColumn("Jumlah");
        detail.addColumn("Total");
        setModelTbl();
    }

    private void setModelTbl() {
        tblTransaksi.setModel(detail);
        tblTransaksi.getColumnModel().getColumn(2).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.getColumnModel().getColumn(3).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.getColumnModel().getColumn(4).setCellRenderer(Parameter.rightRenderer());
        tblTransaksi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        lblTanggal = new javax.swing.JLabel();
        lblNoNota = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        txtNoNota = new javax.swing.JTextField();
        lblReferensi = new javax.swing.JLabel();
        txtReferensi = new javax.swing.JTextField();
        lblTotalHarga = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        lblTotalHarga1 = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblTransaksi);

        lblTanggal.setText("Tanggal :");

        lblNoNota.setText("Nomor Nota :");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtNoNota.setEditable(false);

        lblReferensi.setText("Referensi :");

        txtReferensi.setEditable(false);

        lblTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtTanggal.setEditable(false);

        lblTotalHarga1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalHarga1.setText("Total : ");

        lblFormat.setText("()");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(lblTotalHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNoNota, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblReferensi, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClose)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtReferensi)
                                            .addComponent(txtNoNota)
                                            .addComponent(txtTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFormat)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoNota)
                    .addComponent(txtNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReferensi)
                    .addComponent(txtReferensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblNoNota;
    private javax.swing.JLabel lblReferensi;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblTotalHarga1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtNoNota;
    private javax.swing.JTextField txtReferensi;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
